# Generated by Django 5.1.2 on 2024-11-02 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_option_exam_creates_attempts_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_answers',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_evaluated_answers',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_is_reattempt',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_reattempt_answers',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_reattempt_evaluated_answers',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_reattempt_evaluated_marks',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_reattempt_evaluated_time',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_reattempt_feedback',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_reattempt_is_evaluated',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_reattempt_is_submitted',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_reattempt_time',
        ),
        migrations.RemoveField(
            model_name='option',
            name='id',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_is_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_options',
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attempt_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.exam'),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attempt_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creates',
            name='create_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.exam'),
        ),
        migrations.AlterField(
            model_name='creates',
            name='create_teacher',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_questions',
            field=models.ManyToManyField(related_name='examQuestion', to='API.question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_students',
            field=models.ManyToManyField(related_name='examStudents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AttemptExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.attempts')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.exam')),
            ],
        ),
        migrations.CreateModel(
            name='CreateExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.creates')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.exam')),
            ],
        ),
        migrations.CreateModel(
            name='CUserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.attempts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CUserCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.creates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_question_marks', models.IntegerField()),
                ('exam_question_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.exam')),
                ('exam_question_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
