# Generated by Django 5.1.2 on 2024-11-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_attempts_id_remove_exam_id_remove_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_marks',
            new_name='question_marks_corrent',
        ),
        migrations.AddField(
            model_name='question',
            name='question_marks_wrong',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
        migrations.AddField(
            model_name='question',
            name='question_answer',
            field=models.ManyToManyField(related_name='QuestionOption', to='API.option'),
        ),
    ]
