# Generated by Django 5.1.2 on 2024-11-18 08:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_questionoption_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_time',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='num_attempts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(max_length=255),
        ),
    ]
