# Generated by Django 5.1.2 on 2024-11-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_exam_exam_date_remove_exam_exam_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createexam',
            name='create',
        ),
        migrations.RemoveField(
            model_name='createexam',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='creates',
            name='create_exam',
        ),
        migrations.RemoveField(
            model_name='creates',
            name='create_teacher',
        ),
        migrations.RemoveField(
            model_name='cusercreate',
            name='create',
        ),
        migrations.RemoveField(
            model_name='cuserattempt',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='cuserattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cusercreate',
            name='user',
        ),
        migrations.RenameField(
            model_name='attempts',
            old_name='attempt_evaluated_time',
            new_name='attempt_submission_time',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_evaluated_marks',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_is_evaluated',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='attempt_is_submitted',
        ),
        migrations.AddField(
            model_name='attempts',
            name='attempt_answers',
            field=models.ManyToManyField(related_name='AttemptOption', to='API.option'),
        ),
        migrations.AddField(
            model_name='attempts',
            name='attempt_num_correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempts',
            name='attempt_num_wrong',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AttemptExam',
        ),
        migrations.DeleteModel(
            name='CreateExam',
        ),
        migrations.DeleteModel(
            name='Creates',
        ),
        migrations.DeleteModel(
            name='CUserAttempt',
        ),
        migrations.DeleteModel(
            name='CUserCreate',
        ),
    ]
