# Generated by Django 5.1.2 on 2024-11-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0007_remove_createexam_create_remove_createexam_exam_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attempts",
            name="attempt_num_correct",
        ),
        migrations.RemoveField(
            model_name="attempts",
            name="attempt_num_wrong",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_marks_corrent",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_marks_wrong",
        ),
        migrations.AddField(
            model_name="attempts",
            name="attempt_correct",
            field=models.ManyToManyField(
                related_name="AttemptCorrect", to="API.option"
            ),
        ),
        migrations.AddField(
            model_name="attempts",
            name="attempt_wrong",
            field=models.ManyToManyField(related_name="AttemptWrong", to="API.option"),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, to="API.option"
            ),
            preserve_default=False,
        ),
    ]
