# Generated by Django 5.1.2 on 2024-11-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_attempts_attempt_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='API.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attempt_correct',
            field=models.ManyToManyField(blank=True, null=True, related_name='AttemptCorrect', to='API.option'),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attempt_wrong',
            field=models.ManyToManyField(blank=True, null=True, related_name='AttemptWrong', to='API.option'),
        ),
    ]
