# Generated by Django 5.1.2 on 2024-12-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='attempt_cheats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
