# Generated by Django 5.1.2 on 2024-12-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_attempts_attempt_cheats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='attempt_cheats',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attempt_correct',
            field=models.ManyToManyField(blank=True, related_name='AttemptCorrect', to='API.option'),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attempt_wrong',
            field=models.ManyToManyField(blank=True, related_name='AttemptWrong', to='API.option'),
        ),
    ]
