POST http://127.0.0.1:8000/api/signup 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!", "email": "adam@mail.com", "user_type": "student" }

###

POST http://127.0.0.1:8000/api/signup 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!", "email": "adam@mail.com", "user_type": "teacher" }


###

POST http://127.0.0.1:8000/api/login 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/api/test_token 
Content-Type: application/json
Authorization: Token faed22e8cd08559d5772a3cc03aa3396facb8148

###

GET http://127.0.0.1:8000/api/create_option 
Content-Type: application/json
Authorization: Token faed22e8cd08559d5772a3cc03aa3396facb8148
